apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List every file you want to include in the build
resources:
  - picoclaw-agent-deployment.yaml
  - picoclaw-configmap.yaml
  - picoclaw-gateway-deployment.yaml
  - picoclaw-rbac.yaml
  - picoclaw-workspace-persistentvolumeclaim.yaml

# (Optional) Add a common prefix to all resource names
namePrefix: dev-

# (Optional) Add a label to every single resource automatically
commonLabels:
  environment: dev
  component: agent
  name: picoclaw
