apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List every file you want to include in the build
resources:
- picoclaw-agent-deployment.yaml
- picoclaw-configmap.yaml
- picoclaw-gateway-deployment.yaml
- picoclaw-rbac.yaml
- picoclaw-workspace-persistentvolumeclaim.yaml

# (Optional) Add a common prefix to all resource names
namePrefix: dev-
namespace: picoclaw

# (Optional) Add a label to every single resource automatically
labels:
- includeSelectors: true
  pairs:
    component: agent
    environment: dev
    name: picoclaw
